version: 0.4.4.{build}-{branch}

# branches to build
branches:
  except:
    - gh-pages

skip_tags: true

os: Visual Studio 2015

platform: 
    - X64 
    - Win32

configuration:
    - Debug
    - Release

environment:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_59_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version    

clone_folder: C:\projects\redisclient

build_script:
    - cd C:\projects\redisclient
    - md build
    - cd build
    - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
    - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
    - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" -Durdfdom_DIR="%urdfdom_DIR%" -Durdfdom_headers_DIR="%urdfdom_headers_DIR%" -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..
    - dir 

build:
    project: 

after_build:
before_test:
test_script:
after_test:
on_success:
on_failure:
on_finish:

